# Cli launch command : aws --region us-east-1 cloudformation create-stack --stack-name ernieStackTemplate1 --template-body file://~/cloudRun/cloudForm_ernie.yml --parameters file://~/cloudRun/parameters.json
# Cli delete command : aws --region us-east-1 cloudformation delete-stack --stack-name ernieStackTemplate1
AWSTemplateFormatVersion: "2010-09-09"
Description: AWS CloudFormation Template Trial for Ernie Van Duyne Version 1.00

# note that parameters are what is asked of the user in the user interface when the stack is created from this template
Parameters:
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x.
  KeyNameEVD:
    Description: The key name
    Type: String
  InstanceTypeEVD:
    Description: The type of instance
    Type: String
#Mappings:     # Like a dropdown/lookup table

#Conditions: # like checking if the stack is to build a dev or prod environment and building according to those conditions
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-a4c7edb2 #-- This is my base Linux AMI with no ports open
      InstanceType:
        Ref: InstanceTypeEVD
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName:
        Ref: KeyNameEVD
      UserData:
        Fn::Base64: |
          #!/bin/bash -ex
          touch /home/ernie.txt
          echo "hello" > /home/ernie44.txt
          sudo su
          yum install -y httpd
          echo "<html>I love YAML CloudFormation xmas!!</html>" > /var/www/html/index.html
          cd /var/www/html
          chmod 755 index.html
          service httpd start
          chkconfig httpd on
      Tags:
        - Key: Name
          Value: webserver

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Enable HTTP access via port 80 and SSH access via port 22"
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: '80'
        IpProtocol: tcp
        ToPort: '80'
      - CidrIp: 74.94.81.157/32
        #CidrIp: !Ref SSHLocation
        #CidrIp:
           #Ref: SSHLocation
        FromPort: '22'
        IpProtocol: tcp
        ToPort: '22'
